print("Q1")
print("Hello World!")
print("Q2")
print("Welcome to Python")
print("Q3")
print("siva naga durga.s")
print("Q4")
print("I am learning Python")
print("Q5")
print("Python Programming")
print("Q6")
print("Good Morning")
print("Q7")
print("Welcome Students")
print("Q8")
print("Python is a easy")
print("Q9")
print("My First program")
print("Q10")
print("Hello from Python!")